version: '3.3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpdb_user
      MYSQL_PASSWORD: secret

  wp:
    build: .
    container_name: wp
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp_app:/var/www/html
      - ./conf/certs:/etc/ssl/private:ro
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/wp/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpdb_user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
      WP_ENVIRONMENT_TYPE: local
  wpcli:
    build:
      context: ./conf/wpcli
      dockerfile: Dockerfile
    container_name: wpcli
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp_app:/var/www/html
      #- ./conf/wpcli/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    depends_on:
      - db
      - wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpdb_user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
  
volumes:
  db_data: {}
  wp_app: {}
